version: "3.8"

services:
  relay:
    image: ghcr.io/lancetm714/whatsapp-sms-relay:main
    container_name: whatsapp-sms-relay
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./wwebjs_auth:/app/wwebjs_auth
    restart: unless-stopped
